### ISSUE TITLE
Client not updating

### ISSUE THREAD

**Issue by Shrubbity** [neowutran/ShinraMeter#118]
Here's the error log:

`2016-04-30 11:51:02,955 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=0.95): #####
An exception occurred during a WebClient request.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at DamageMeter.AutoUpdate.UpdateManager.Download() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 75
   at DamageMeter.AutoUpdate.UpdateManager.<Update>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<CheckUpdate>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<App_OnStartup>d__2.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 47
System
System.Net.WebException: An exception occurred during a WebClient request. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at DamageMeter.AutoUpdate.UpdateManager.Download() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 75
   at DamageMeter.AutoUpdate.UpdateManager.<Update>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<CheckUpdate>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<App_OnStartup>d__2.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 47
System.Collections.ListDictionaryInternal
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
Void DownloadFile(System.Uri, System.String)
2016-04-30 11:51:23,196 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=0.95): #####
An exception occurred during a WebClient request.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at DamageMeter.AutoUpdate.UpdateManager.Download() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 75
   at DamageMeter.AutoUpdate.UpdateManager.<Update>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<CheckUpdate>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<App_OnStartup>d__2.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 47
System
System.Net.WebException: An exception occurred during a WebClient request. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at DamageMeter.AutoUpdate.UpdateManager.Download() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 75
   at DamageMeter.AutoUpdate.UpdateManager.<Update>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<CheckUpdate>d__5.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DamageMeter.UI.App.<App_OnStartup>d__2.MoveNext() in E:\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 47
System.Collections.ListDictionaryInternal
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
Void DownloadFile(System.Uri, System.String)`

**Comment by FusenSho** [comment]
Cant update aswell.
Also you cant donload the new version directly since the OVH link needs authentication.

**Comment by Gl0** [comment]
There are some problems with update server, @neowutran is working on it.

**Comment by neowutran** [comment]
fixed
