### ISSUE TITLE
Error.txt

### ISSUE THREAD

**Issue by michise** [neowutran/ShinraMeter#146]
I'm new to anythning to do with this i thought i followed the instructions well..

2016-07-02 22:30:18,415 [7] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=1.14): #####
Object reference not set to an instance of an object.
   at DamageMeter.CopyPaste.Copy(StatsSummary statsSummary, Skills skills, AbnormalityStorage abnormals, Boolean timedEncounter, String header, String content, String footer, String orderby, String order) in G:\ShinraMeter\DamageMeter.Core\CopyPaste.cs:line 111
   at DamageMeter.NetworkController.CopyThread(StatsSummary stats, Skills skills, AbnormalityStorage abnormals, Boolean timedEncounter, CopyKey copy) in G:\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 173
   at DamageMeter.NetworkController.<>c__DisplayClass72_0.<PacketAnalysisLoop>b__0() in G:\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 197
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
DamageMeter
System.NullReferenceException: Object reference not set to an instance of an object.
   at DamageMeter.CopyPaste.Copy(StatsSummary statsSummary, Skills skills, AbnormalityStorage abnormals, Boolean timedEncounter, String header, String content, String footer, String orderby, String order) in G:\ShinraMeter\DamageMeter.Core\CopyPaste.cs:line 111
   at DamageMeter.NetworkController.CopyThread(StatsSummary stats, Skills skills, AbnormalityStorage abnormals, Boolean timedEncounter, CopyKey copy) in G:\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 173
   at DamageMeter.NetworkController.<>c__DisplayClass72_0.<PacketAnalysisLoop>b__0() in G:\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 197
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

System.String Copy(DamageMeter.Database.Structures.StatsSummary, DamageMeter.Database.Structures.Skills, Tera.Game.Abnormality.AbnormalityStorage, Boolean, System.String, System.String, System.String, System.String, System.String)

**Comment by neowutran** [comment]
should be fixed with next release
