### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Cupcakes123** [neowutran/ShinraMeter#202]
Can someone please explain to me what this means?
My meter suddenly stopped registering new fights (I changed the priority to false btw)
2016-09-22 14:00:20,623 [19] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Tera.Game.MessageFactory.Instantiate(String opCodeName, TeraMessageReader reader) in J:\c\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 107
   at Tera.Game.MessageFactory.Create(Message message) in J:\c\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 114
   at DamageMeter.NetworkController.PacketAnalysisLoop() in J:\c\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 299
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UnicodeEncoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at System.IO.BinaryReader.InternalReadOneChar()
   at System.IO.BinaryReader.Read()
   at System.IO.BinaryReader.ReadChar()
   at Tera.Game.TeraMessageReader.ReadTeraString() in J:\c\ShinraMeter\TeraCommon\Game\Services\TeraMessageReader.cs:line 57
   at Tera.Game.Messages.S_OTHER_USER_APPLY_PARTY..ctor(TeraMessageReader reader) in J:\c\ShinraMeter\TeraCommon\Game\Messages\Server\S_OTHER_USER_APPLY_PARTY.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Tera.Game.MessageFactory.Instantiate(String opCodeName, TeraMessageReader reader) in J:\c\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 107
   at Tera.Game.MessageFactory.Create(Message message) in J:\c\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 114
   at DamageMeter.NetworkController.PacketAnalysisLoop() in J:\c\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 299
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UnicodeEncoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at System.IO.BinaryReader.InternalReadOneChar()
   at System.IO.BinaryReader.Read()
   at System.IO.BinaryReader.ReadChar()
   at Tera.Game.TeraMessageReader.ReadTeraString() in J:\c\ShinraMeter\TeraCommon\Game\Services\TeraMessageReader.cs:line 57
   at Tera.Game.Messages.S_OTHER_USER_APPLY_PARTY..ctor(TeraMessageReader reader) in J:\c\ShinraMeter\TeraCommon\Game\Messages\Server\S_OTHER_USER_APPLY_PARTY.cs:line 17
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Cupcakes123** [comment]
2016-09-22 14:49:35,016 [18] ERROR ShinraMeter [(null)] - ##### (version=1.45):
##### Debug: Normal priority Received: 20104724
20104761: 20
20104781: 20
20104801: 20
20104821: 42
20104863: 47
20104910: 47
20104957: 21
20104978: 47
20105025: 37
20105062: 20
Queue length:1001
New Queue length:1001

**Comment by Gl0** [comment]
Rechecked debug log, seems there are a bunch of missed packets logged before crash. Try to update network card drivers or try to play via another network interface.

**Comment by Cupcakes123** [comment]
Ok I figured out what seems to be wrong. Not sure if it's a bug or a big coincidence. I copied my friend's config which is 1. Count only party members 2. Invisible when no stats 3. Stay topmost and 4. Enable chat notifications and my issue stopped.

Before I changed the configurations; it used to stop registering a new fight.

**Comment by Cupcakes123** [comment]
Oh, even changing the priority to false still didn't work before until the notifications :x

**Comment by Gl0** [comment]
The only things in config that may affect this issue is winpcap and priority.

**Comment by Cupcakes123** [comment]
Oh okay, I see. One last question, if you have 1.45, do the stats upload to moongourd automatically?

**Comment by neowutran** [comment]
no, to enable that you have to check the option "export to site" in the settings windows
