### ISSUE TITLE
pls update TWserver

### ISSUE THREAD

**Issue by q848899** [neowutran/ShinraMeter#211]
TWserver 10.06 update 
pls XD

**Comment by herowinb** [comment]
Yeah, got error and crash shinrameter. Here log
`2016-10-07 15:26:49,136 [6] ERROR ShinraMeter [(null)] - ##### (version=1.48):
##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   at DamageMeter.NetworkController.PacketAnalysisLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'G:\ShinraMeterV1.30\resources\data\opcodes\306697.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   at DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   at DamageMeter.NetworkController.PacketAnalysisLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.FileNotFoundException: Could not find file 'G:\ShinraMeterV1.30\resources\data\opcodes\306697.txt'.
File name: 'G:\ShinraMeterV1.30\resources\data\opcodes\306697.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   at DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
`

**Comment by Gl0** [comment]
we can't update until someone send us new opcodes and decrypted datacenter files

**Comment by q848899** [comment]
There is no simple way to get ?

**Comment by neowutran** [comment]
someone can test that? 
https://cloud.neowutran.ovh/index.php/s/qz27wQgaylWsvGz

**Comment by q848899** [comment]
no error but no work
 Able to connect to the server  but no  data

**Comment by q848899** [comment]
i copy 306697.txt to Before use hit monsters Error occurred 
2016-10-08 02:18:04,881 [8] ERROR ShinraMeter [(null)] - ##### (version=1.48):
##### CRASH #####
调用的目标发生了异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   在 DamageMeter.NetworkController.PacketAnalysisLoop()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Tera.Game.SkillResult..ctor(EachSkillResultServerMessage message, EntityTracker entityRegistry, PlayerTracker playerTracker, SkillDatabase skillDatabase, PetSkillDatabase petSkillDatabase)
   在 DamageMeter.Processing.S_EACH_SKILL_RESULT..ctor(EachSkillResultServerMessage message)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   在 DamageMeter.NetworkController.PacketAnalysisLoop()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Tera.Game.SkillResult..ctor(EachSkillResultServerMessage message, EntityTracker entityRegistry, PlayerTracker playerTracker, SkillDatabase skillDatabase, PetSkillDatabase petSkillDatabase)
   在 DamageMeter.Processing.S_EACH_SKILL_RESULT..ctor(EachSkillResultServerMessage message)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Gl0** [comment]
Check this one https://storage.sbg1.cloud.ovh.net/v1/AUTH_a2ab8c541a2f4f82b2bc1d39f82a10be/DATA/ShinraMeterV.zip

**Comment by q848899** [comment]
equally no data

**Comment by herowinb** [comment]
can't detecte server

**Comment by q848899** [comment]
I can connect to the server icon to come out  but hit monsters Error occurred

**Comment by Gl0** [comment]
strange Are you sure that first link (https://cloud.neowutran.ovh/index.php/s/qz27wQgaylWsvGz) not working?

**Comment by herowinb** [comment]
well, it working after turn off my firewall. No problems found

**Comment by q848899** [comment]
You can use ?  
Why I use no data  I tried again.

**Comment by Gl0** [comment]
@herowinb which one?=)

**Comment by herowinb** [comment]
Which your version (https://cloud.neowutran.ovh/index.php/s/qz27wQgaylWsvGz). But when i turn off it and try again it not working xD

**Comment by Gl0** [comment]
it's probably auto downgraded to previous version

**Comment by q848899** [comment]
ok  I use VPN link so no work 
Direct connection  is working but before modify server list is work

**Comment by herowinb** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8396689/19202244/94e3900e-8cfb-11e6-8e04-e6b79786629e.png)
Yeah, it worked

**Comment by Gl0** [comment]
@q848899  for vpn you probably doesn't need to change server.txt, you need to enable raw sockets and allow incoming traffic in firewall.

**Comment by q848899** [comment]
Not modify server.txt Unable to read server 
I don't know how to do it. I should have not installed a firewall 
but before modify server.txt is work

**Comment by Gl0** [comment]
How do you modify it? in 99% cases it's unnecessary.

**Comment by q848899** [comment]
220.228.174.67 TW 2804 提雅拉尼亞
113.108.225.64 TW 2800 提雅拉尼亞
113.108.224.64 TW 2801 提雅拉尼亞
113.108.225.63 TW 2802 提雅拉尼亞
113.108.222.64 TW 2803 提雅拉尼亞
113.108.225.34 TW 2805 提雅拉尼亞
Not modify server.txt Unable to read server 
Those are VPN ip

**Comment by Gl0** [comment]
That's bad strings

**Comment by Gl0** [comment]
what vpn solution do you use?

**Comment by q848899** [comment]
![1](https://cloud.githubusercontent.com/assets/16863960/19203108/20f011a6-8d08-11e6-9d9a-3f51b5bfb3a3.jpg)
i use VPN or no use VPN Here IP is not the same 
Not modify server.txt Unable to read server

**Comment by q848899** [comment]
Because each VPN connection is not the same as IP 
so copy Many article 
 So change any ip is work

**Comment by Gl0** [comment]
Yeah, seems you are in that 1% of users, who need overrides for it. But anyway, you've done it wrong.
it should be something like this: http://pastebin.com/0d9RUqyg

**Comment by Gl0** [comment]
or better http://pastebin.com/89z3Gt60 - much clearer

**Comment by q848899** [comment]
You mean like this on work?

**Comment by q848899** [comment]
I used to be able to do that. 
But this time I think I should not write the wrong problem 
This is connected to server but no data

**Comment by Gl0** [comment]
yeah, on 1.49.
You should not change any existing string in servers.txt,  just add your vpn ip's, followed by region, 2 spaces and some identifier to see where meter is connected at that moment.

**Comment by q848899** [comment]
![11](https://cloud.githubusercontent.com/assets/16863960/19204725/070080d8-8d11-11e6-8171-f5f8023a3489.jpg)
different 
![22](https://cloud.githubusercontent.com/assets/16863960/19204727/0811ab96-8d11-11e6-82fb-ddc3eeab7977.jpg)
Connect up but no data

**Comment by Gl0** [comment]
It should change from vpn to your server name when it receive s_login packet.
Recheck firewall rule settings

**Comment by q848899** [comment]
Anyway, thanks for the update. 
I don't seem to be using this VPN. 
I'll think of something else.  XD

**Comment by q848899** [comment]
@neowutran 
Can not send a No change Raw Socket Version for me?
Because I see you have a change in the update log
because All my friends To use change server.txt To use is  All no data 
Not be unable to connect to the server 
After choosing a character  the guild icon will  no change 
Firewall is not involved Because I've stopped the firewall service.
1.48Version before  We are all normal.  so please Thanks

**Comment by herowinb** [comment]
raw sockets have problem now, it stuck after 2-5mins work. 
If you use wincap or npcap and wincap mode it will be fine.

**Comment by q848899** [comment]
I don't understand
I installed wincap Previous versions by change
\resources\config\window.xml this file <winpcap>true</winpcap>or false it is available that but this no effect

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/commit/0ffd174af0cded4d82e16349c0379e0e8200e053

**Comment by q848899** [comment]
1.50 version everything normal 
You are wonderful !
thanks!!!

**Comment by Gl0** [comment]
@q848899 BTW, have you tried 1.50 with vpn without changing servers.txt?

**Comment by q848899** [comment]
yeah 
I'm testing it now. It's still not working. Unable to connect to the server

**Comment by Gl0** [comment]
Ok, I'll add servers override file, so that you should not change servers.txt each update.

**Comment by q848899** [comment]
Is not a problem 
But thank you.

**Comment by Gl0** [comment]
Can any of you send me TW(or CHN, not sure which one is used by TW client now) font?
'TERA\S1Game\CookedPC\Art_Data\Packages\S1UI\fonts_*.gpk'
And whether tera language can be switched from one to other if both fonts are there.

**Comment by q848899** [comment]
http://pan.baidu.com/s/1c2ifK56
Is this file？
This forum limits the size of I only use domestic 
Don't know if you can download

**Comment by Gl0** [comment]
Thanks, I've already have this. https://github.com/neowutran/ShinraMeter/issues/207#issuecomment-255567332
