### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ShiSenpai** [neowutran/ShinraMeter#364]
My meter was working fine last night, but this morning it stopped completely with a "Fatal Error" Message: http://prntscr.com/frfxio

Error Log:
2017-07-04 12:10:01,891 [5] ERROR ShinraMeter [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at DamageMeter.PacketProcessingFactory.Process(ParsedMessage message) in J:\c\ShinraMeter\DamageMeter.Core\PacketProcessingFactory.cs:line 154
   at DamageMeter.NetworkController.PacketAnalysisLoop() in J:\c\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 378
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'C:\Games\ShinraMeterV2.02\resources\data\opcodes\313578.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in J:\c\ShinraMeter\TeraCommon\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in J:\c\ShinraMeter\TeraCommon\Game\Services\OpCodeNamer.cs:line 23
   at DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message) in J:\c\ShinraMeter\DamageMeter.Core\Processing\C_CHECK_VERSION.cs:line 15
   at lambda_method(Closure , C_CHECK_VERSION )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at DamageMeter.PacketProcessingFactory.Process(ParsedMessage message) in J:\c\ShinraMeter\DamageMeter.Core\PacketProcessingFactory.cs:line 154
   at DamageMeter.NetworkController.PacketAnalysisLoop() in J:\c\ShinraMeter\DamageMeter.Core\NetworkController.cs:line 378
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.FileNotFoundException: Could not find file 'C:\Games\ShinraMeterV2.02\resources\data\opcodes\313578.txt'.
File name: 'C:\Games\ShinraMeterV2.02\resources\data\opcodes\313578.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in J:\c\ShinraMeter\TeraCommon\Game\Services\OpCodeNamer.cs:line 37
   at Tera.Game.OpCodeNamer..ctor(String filename) in J:\c\ShinraMeter\TeraCommon\Game\Services\OpCodeNamer.cs:line 23
   at DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message) in J:\c\ShinraMeter\DamageMeter.Core\Processing\C_CHECK_VERSION.cs:line 15
   at lambda_method(Closure , C_CHECK_VERSION )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Foglio1024** [comment]
Meter requires update after patches. It will be released later today.

**Comment by ShiSenpai** [comment]
So later today when the update comes out will I have to reinstall or will it just magically work?

**Comment by Foglio1024** [comment]
You'll be asked to download the update when you start the application

**Comment by ShiSenpai** [comment]
Okay, any idea of EST for the update?

**Comment by neowutran** [comment]
released few hours ago

**Comment by ShiSenpai** [comment]
Just finally got the update notification now
