### ISSUE TITLE
different value

### ISSUE THREAD

**Issue by NEON714** [neowutran/ShinraMeter#381]
why is my shinra displays different results than the ones shown in moongourd? whereas my friend's shinra showed the same result with moongourd.

**Comment by neowutran** [comment]
if it is in HH, because of the huge distance, not everyone saw the same skills, so moongourd try to take the most accurate one. 
If it is not in HH, then give me more infos because this cannot happens, maybe your meter version is outdated

**Comment by NEON714** [comment]
it is in all dungeons, and almost every time. im sorry, i dont know how to give you more infos. and my meter is always uptodate, although only minor updates (i dont use auto update feature, i always download it right from the site if auto update triggered).

**Comment by Gl0** [comment]
minor updates = db updates, each one can fix bad counting last 2 weeks.
+ check error.log, may be there are some issues with skipped packets ( or in your friend's error..log)

**Comment by NEON714** [comment]
this is it

2017-09-05 08:58:15,065 [25] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 6915616
6915681: 28
Queue length:501
New Queue length:501
Skipping bytes:65
2017-09-05 12:30:09,376 [10] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 16134
17546: 1412
Queue length:501
New Queue length:423
Skipping bytes:109425
2017-09-05 12:30:39,421 [10] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 190888
192300: 1412
Queue length:501
New Queue length:462
Skipping bytes:56480
2017-09-05 12:30:56,891 [19] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 282668
284080: 1412
Queue length:501
New Queue length:498
Skipping bytes:5648
2017-09-05 12:31:05,845 [19] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 340560
341972: 1412
Queue length:501
New Queue length:497
Skipping bytes:5937
2017-09-06 13:08:46,546 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=2.10.9185370): #####
The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at DamageMeter.AutoUpdate.UpdateManager.GetDiff(KeyValuePair`2 file)
   at DamageMeter.AutoUpdate.UpdateManager.<>c__DisplayClass12_0.<HashedUpdate>b__4(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at DamageMeter.AutoUpdate.UpdateManager.HashedUpdate()
   at DamageMeter.UI.App.<CheckUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DamageMeter.UI.App.<App_OnStartup>d__4.MoveNext()
System
System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at DamageMeter.AutoUpdate.UpdateManager.GetDiff(KeyValuePair`2 file)
   at DamageMeter.AutoUpdate.UpdateManager.<>c__DisplayClass12_0.<HashedUpdate>b__4(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at DamageMeter.AutoUpdate.UpdateManager.HashedUpdate()
   at DamageMeter.UI.App.<CheckUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DamageMeter.UI.App.<App_OnStartup>d__4.MoveNext()
System.Collections.ListDictionaryInternal

Int32 Read(Byte[], Int32, Int32)
2017-09-06 13:15:45,436 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=2.10.9185370): #####
The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at DamageMeter.AutoUpdate.UpdateManager.GetDiff(KeyValuePair`2 file)
   at DamageMeter.AutoUpdate.UpdateManager.<>c__DisplayClass12_0.<HashedUpdate>b__4(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at DamageMeter.AutoUpdate.UpdateManager.HashedUpdate()
   at DamageMeter.UI.App.<CheckUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DamageMeter.UI.App.<App_OnStartup>d__4.MoveNext()
System
System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at DamageMeter.AutoUpdate.UpdateManager.GetDiff(KeyValuePair`2 file)
   at DamageMeter.AutoUpdate.UpdateManager.<>c__DisplayClass12_0.<HashedUpdate>b__4(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at DamageMeter.AutoUpdate.UpdateManager.HashedUpdate()
   at DamageMeter.UI.App.<CheckUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DamageMeter.UI.App.<App_OnStartup>d__4.MoveNext()
System.Collections.ListDictionaryInternal

Int32 Read(Byte[], Int32, Int32)
2017-09-06 15:06:59,466 [11] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 153539
154951: 1412
Queue length:501
New Queue length:492
Skipping bytes:14120
2017-09-06 15:07:00,408 [6] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 194924
196336: 1412
Queue length:501
New Queue length:498
Skipping bytes:5648
2017-09-06 15:07:06,853 [6] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 320776
322188: 1412
Queue length:501
New Queue length:486
Skipping bytes:22592
2017-09-06 15:07:08,659 [25] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 346192
347604: 1412
Queue length:501
New Queue length:465
Skipping bytes:50067
2017-09-06 15:07:16,494 [19] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 430320
431732: 1412
Queue length:501
New Queue length:498
Skipping bytes:5648
2017-09-06 15:07:17,076 [11] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 447264
448676: 1412
Queue length:501
New Queue length:498
Skipping bytes:5648
2017-09-06 15:07:21,972 [16] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 512216
513628: 1412
Queue length:501
New Queue length:499
Skipping bytes:3196
2017-09-06 15:07:28,260 [6] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 535178
536590: 1412
Queue length:501
New Queue length:499
Skipping bytes:2847
2017-09-06 15:09:14,715 [11] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 673425
673790: 137
Queue length:501
New Queue length:501
Skipping bytes:365
2017-09-06 15:11:13,762 [6] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 838820
840232: 1412
Queue length:501
New Queue length:498
Skipping bytes:3980
2017-09-07 14:28:44,668 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=2.10.3dd1e51): #####
The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at DamageMeter.AutoUpdate.UpdateManager.GetDiff(KeyValuePair`2 file)
   at DamageMeter.AutoUpdate.UpdateManager.<>c__DisplayClass12_0.<HashedUpdate>b__4(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at DamageMeter.AutoUpdate.UpdateManager.HashedUpdate()
   at DamageMeter.UI.App.<CheckUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DamageMeter.UI.App.<App_OnStartup>d__4.MoveNext()
System
System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at DamageMeter.AutoUpdate.UpdateManager.GetDiff(KeyValuePair`2 file)
   at DamageMeter.AutoUpdate.UpdateManager.<>c__DisplayClass12_0.<HashedUpdate>b__4(KeyValuePair`2 x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at DamageMeter.AutoUpdate.UpdateManager.HashedUpdate()
   at DamageMeter.UI.App.<CheckUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DamageMeter.UI.App.<App_OnStartup>d__4.MoveNext()
System.Collections.ListDictionaryInternal

Int32 Read(Byte[], Int32, Int32)
2017-09-07 16:12:34,700 [18] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 13479212
13479483: 1412
Queue length:501
New Queue length:496
Skipping bytes:6269
2017-09-08 14:09:15,858 [11] ERROR ShinraMeter [(null)] - Normal priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces Received: 9601194
9601245: 51
Queue length:501
New Queue length:501
Skipping bytes:51

**Comment by Gl0** [comment]
ups, that commit should close other issue.
