### ISSUE TITLE
error, error and error

### ISSUE THREAD

**Issue by NEON714** [neowutran/ShinraMeter#394]
whats wrong with this one?

> 2017-11-03 19:11:22,605 [15] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 19:11:22,637 [7] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 19:25:11,779 [6] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 19:25:11,784 [14] ERROR ShinraMeter [(null)] - PacketExport: Export data to tmp file
2017-11-03 19:25:14,425 [11] ERROR ShinraMeter [(null)] - PacketExport: Compress file
2017-11-03 19:25:21,768 [6] ERROR ShinraMeter [(null)] - PacketExport: Encrypt file
2017-11-03 19:25:21,931 [11] ERROR ShinraMeter [(null)] - PacketExport: Send file
2017-11-03 19:25:21,947 [10] ERROR ShinraMeter [(null)] - PacketExport: Send hash: E7BE437818408CF7BC25D9915DE3374E7CC6E14B
2017-11-03 19:25:22,573 [14] ERROR ShinraMeter [(null)] - ##### CRASH #####
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DamageMeter.PacketsExporter.Send(String filename, UInt32 version)
   at DamageMeter.PacketsExporter.Export(EncounterBase teradpsData, NpcEntity entity)
   at DamageMeter.DataExporter.<>c__DisplayClass7_0.<AutomatedExport>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DamageMeter.PacketsExporter.Send(String filename, UInt32 version)
   at DamageMeter.PacketsExporter.Export(EncounterBase teradpsData, NpcEntity entity)
   at DamageMeter.DataExporter.<>c__DisplayClass7_0.<AutomatedExport>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

> System.Collections.ListDictionaryInternal
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
Void ThrowIfExceptional(Boolean)
2017-11-03 19:38:06,605 [7] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 19:38:06,605 [6] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 19:44:43,147 [15] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 19:44:43,148 [16] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 19:50:31,721 [19] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 19:50:31,721 [15] ERROR ShinraMeter [(null)] - PacketExport: Option not activated, exiting
2017-11-03 19:55:23,109 [10] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 19:55:23,111 [17] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 19:57:02,427 [15] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 19:57:02,428 [3] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 20:30:41,742 [11] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 20:30:41,758 [15] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 20:37:18,285 [11] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 20:37:18,285 [18] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 20:43:13,225 [18] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 20:43:13,254 [12] ERROR ShinraMeter [(null)] - PacketExport: Export data to tmp file
2017-11-03 20:43:15,036 [15] ERROR ShinraMeter [(null)] - PacketExport: Compress file
2017-11-03 20:43:23,810 [11] ERROR ShinraMeter [(null)] - PacketExport: Encrypt file
2017-11-03 20:43:23,828 [13] ERROR ShinraMeter [(null)] - PacketExport: Send file
2017-11-03 20:43:23,828 [12] ERROR ShinraMeter [(null)] - PacketExport: Send hash: 73A597834FD41A8C0A0B6AAAC0946F805FB5F8C3
2017-11-03 20:43:24,450 [18] ERROR ShinraMeter [(null)] - ##### CRASH #####
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DamageMeter.PacketsExporter.Send(String filename, UInt32 version)
   at DamageMeter.PacketsExporter.Export(EncounterBase teradpsData, NpcEntity entity)
   at DamageMeter.DataExporter.<>c__DisplayClass7_0.<AutomatedExport>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DamageMeter.PacketsExporter.Send(String filename, UInt32 version)
   at DamageMeter.PacketsExporter.Export(EncounterBase teradpsData, NpcEntity entity)
   at DamageMeter.DataExporter.<>c__DisplayClass7_0.<AutomatedExport>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

> System.Collections.ListDictionaryInternal
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
Void ThrowIfExceptional(Boolean)
2017-11-03 20:50:08,461 [5] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 20:50:08,461 [12] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 20:57:26,415 [13] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 20:57:26,416 [17] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
2017-11-03 21:03:56,152 [17] ERROR ShinraMeter [(null)] - PacketExport: Start
2017-11-03 21:03:56,153 [12] ERROR ShinraMeter [(null)] - PacketExport: Option not activated, exiting

**Comment by neowutran** [comment]
https error while trying to connect to my server ^^ 
I already pushed a fix, so this error will disapear with V2.18
