### ISSUE TITLE
Shinra "Crash" when used in Classic EU Server with more than 1 character on account

### ISSUE THREAD

**Issue by Inzanity99** [neowutran/ShinraMeter#458]
When using shinra with more than 1 chracter on the account, Shinra will crash once you reach the character selection screen.
Single Character works without issues.

Error Log:
```
2019-02-14 14:23:42,976 [13] ERROR ShinraMeter [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader)
   at Tera.Game.MessageFactory.Create(Message message)
   at DamageMeter.PacketProcessor.PacketAnalysisLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Tera.Game.Messages.S_GET_USER_LIST..ctor(TeraMessageReader reader)
   at lambda_method(Closure , TeraMessageReader )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader)
   at Tera.Game.MessageFactory.Create(Message message)
   at DamageMeter.PacketProcessor.PacketAnalysisLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Tera.Game.Messages.S_GET_USER_LIST..ctor(TeraMessageReader reader)
   at lambda_method(Closure , TeraMessageReader )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
```

**Comment by Gl0** [comment]
known issue, need to change the way meter detect user's guild.
