### ISSUE TITLE
excel export is not working.

### ISSUE THREAD

**Issue by JackSal1** [neowutran/ShinraMeter#497]
2021-07-25 00:20:39,139 [14] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Error saving file C:\Users\dighe\Documents\ShinraMeter\황금의 미궁(시험의 던전)\폭군 바라코스 2021-07-25 00-20-38 톡.xlsx
   at OfficeOpenXml.ExcelPackage.Save()
   at DamageMeter.ExcelExporter.ExcelSave(ExtendedStats exdata, String userName, Boolean manual) in J:\c\ShinraMeter\DamageMeter.Core\Exporter\ExcelExporter.cs:line 371
   at DamageMeter.DataExporter.<>c__DisplayClass7_0.<AutomatedExport>b__0() in J:\c\ShinraMeter\DamageMeter.Core\Exporter\DataExporter.cs:line 237
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
EPPlus
System.InvalidOperationException: Error saving file C:\Users\dighe\Documents\ShinraMeter\황금의 미궁(시험의 던전)\폭군 바라코스 2021-07-25 00-20-38 톡.xlsx
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\dighe\Documents\ShinraMeter\황금의 미궁(시험의 던전)\폭군 바라코스 2021-07-25 00-20-38 톡.xlsx' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at OfficeOpenXml.ExcelPackage.Save()
   --- End of inner exception stack trace ---
   at OfficeOpenXml.ExcelPackage.Save()
   at DamageMeter.ExcelExporter.ExcelSave(ExtendedStats exdata, String userName, Boolean manual) in J:\c\ShinraMeter\DamageMeter.Core\Exporter\ExcelExporter.cs:line 371
   at DamageMeter.DataExporter.<>c__DisplayClass7_0.<AutomatedExport>b__0() in J:\c\ShinraMeter\DamageMeter.Core\Exporter\DataExporter.cs:line 237
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.UnauthorizedAccessException: Access to the path 'C:\Users\dighe\Documents\ShinraMeter\황금의 미궁(시험의 던전)\폭군 바라코스 2021-07-25 00-20-38 톡.xlsx' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at OfficeOpenXml.ExcelPackage.Save()
Void Save()

why not working?

**Comment by Gl0** [comment]
`Access to the path 'C:\Users\dighe\Documents\ShinraMeter\황금의 미궁(시험의 던전)\폭군 바라코스 2021-07-25 00-20-38 톡.xlsx' is denied.`
Check access rights for that folder or change excel save directory in ./resources/config/window.xml

**Comment by JackSal1** [comment]
Okay, solved it. i changed the directory. thank you.
