### ISSUE TITLE
Shinra not reading Menma Tera server

### ISSUE THREAD

**Issue by Kareyi** [neowutran/ShinraMeter#506]
Hello

Unpacked shinra and installed .net core 3.1.426 as well, it didn't show any data, however UI was visible in the game.
Tried installing npcap with api enabled, didn't fix the issue. Also tried win10pcap, it didn't solve it either. Firewall excemption was added as well, tried unchecking npcap usage in shinra, I've run everything with admin.

I thought it's compatibility issue as I am using win 11 however log shows something is going on with the autoupdate. Could you please check below?

2023-07-30 02:35:48,745 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=2.96.19de775): #####
The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_0.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at DamageMeter.AutoUpdate.UpdateManager.NoNewHashes() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 180
   at DamageMeter.AutoUpdate.UpdateManager.IsUpToDate() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 109
   at DamageMeter.UI.App.CheckUpdate() in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 150
   at DamageMeter.UI.App.App_OnStartup(Object sender, StartupEventArgs e) in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 88
System.Net.Requests
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_0.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at DamageMeter.AutoUpdate.UpdateManager.NoNewHashes() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 180
   at DamageMeter.AutoUpdate.UpdateManager.IsUpToDate() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 109
   at DamageMeter.UI.App.CheckUpdate() in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 150
   at DamageMeter.UI.App.App_OnStartup(Object sender, StartupEventArgs e) in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 88
System.Collections.ListDictionaryInternal

System.Net.WebResponse EndGetResponse(System.IAsyncResult)
2023-07-30 02:36:29,499 [17] ERROR Data.BasicTeraData [(null)] - DroppedPackets 49, InterfaceDroppedPackets 0, ReceivedPackets 1536
2023-07-30 02:39:20,663 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### UPDATE EXCEPTION (version=2.96.19de775): #####
The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_0.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at DamageMeter.AutoUpdate.UpdateManager.NoNewHashes() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 180
   at DamageMeter.AutoUpdate.UpdateManager.IsUpToDate() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 109
   at DamageMeter.UI.App.CheckUpdate() in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 150
   at DamageMeter.UI.App.App_OnStartup(Object sender, StartupEventArgs e) in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 88
System.Net.Requests
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_0.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at DamageMeter.AutoUpdate.UpdateManager.NoNewHashes() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 180
   at DamageMeter.AutoUpdate.UpdateManager.IsUpToDate() in J:\c\ShinraMeter\DamageMeter.AutoUpdate\UpdateManager.cs:line 109
   at DamageMeter.UI.App.CheckUpdate() in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 150
   at DamageMeter.UI.App.App_OnStartup(Object sender, StartupEventArgs e) in J:\c\ShinraMeter\DamageMeter.UI\App.xaml.cs:line 88
System.Collections.ListDictionaryInternal

System.Net.WebResponse EndGetResponse(System.IAsyncResult)

**Comment by mxpicu** [comment]
Hi, i have the same ERROR , can you help me ?
