### ISSUE TITLE
Error after starting Shinra Meter

### ISSUE THREAD

**Issue by Concratex24** [neowutran/ShinraMeter#508]
I'm getting always the same issues after starting Shinra, i've already tried everything..

```
2024-11-17 18:24:55,053 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
2024-11-17 18:41:46,842 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
2024-11-17 18:46:21,203 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 158
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 384
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 158
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 384
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
2024-11-17 18:51:21,718 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
2024-11-17 19:00:43,087 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 160
   at Tera.Game.MessageFactory.Create(Message message) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 166
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
2024-11-17 19:11:45,142 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 158
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 158
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
2024-11-17 19:15:23,263 [5] ERROR Data.BasicTeraData [(null)] - ##### CRASH #####
Exception has been thrown by the target of an invocation.
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 158
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Private.CoreLib
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Services\MessageFactory.cs:line 158
   at DamageMeter.PacketProcessor.PacketAnalysisLoop() in E:\Repos\ShinraMeter\DamageMeter.Core\PacketProcessor.cs:line 449
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
System.Collections.ListDictionaryInternal
System.ArgumentException: Unexpected raw value for RaceGenderClass 4194665
   at Tera.Game.RaceGenderClass.set_Raw(Int32 value) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 24
   at Tera.Game.RaceGenderClass..ctor(Int32 raw) in E:\Repos\ShinraMeter\TeraCommon\Game\RaceGenderClass.cs:line 58
   at Tera.Game.Messages.LoginServerMessage..ctor(TeraMessageReader reader) in E:\Repos\ShinraMeter\TeraCommon\Game\Messages\Server\LoginServerMessage.cs:line 11
   at lambda_method22(Closure, TeraMessageReader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
```

maybe someone can help me.

**Comment by mxpicu** [comment]
did you solve it ? i have the same problem

**Comment by tiredofchoosing** [comment]
@Concratex24 @mxpicu 
If you guys are still interested. This happens due to ReleaseVersion checks at [this line](https://github.com/neowutran/Tera/blob/d1b489149a90b9f8c8bd2f9e2518198da8fe1190/Game/Messages/Server/LoginServerMessage.cs#L8)

Looks like your client sends wrong version in C_LOGIN_ARBITER so that RaceGenderClass type receives wrong raw data and crashes the app.

It can be fixed by adding following code snippet to C_LOGIN_ARBITER.cs in Tera.Core project before `reader.Factory.ReleaseVersion = Version;` line:
```
var arg = Environment.GetCommandLineArgs().FirstOrDefault(a => a.StartsWith("--fake-version="));
if (arg != null)
{
    var fakeVersionStr = arg.Split('=')[1];
    if (int.TryParse(fakeVersionStr, out int fakeVersion))
    {
        Version = fakeVersion;
    }
}
```

After building and replacing Tera.Core.dll you will be able to run exeutable with `--fake-version=10002` argument. This worked for me at least.

You can also take updated Tera.Core.dll from [here](https://github.com/tiredofchoosing/Tera/releases/tag/v1.0)
