### ISSUE TITLE
[Crash] "Fatal error has occured"

### ISSUE THREAD

**Issue by mohrad-m** [neowutran/ShinraMeter#82]
`2016-04-02 16:36:52,672 [10] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.80): #####
Attempted to divide by zero.
   at DamageMeter.DataExporter.ToTeraDpsApi(SDespawnNpc despawnNpc)
   at DamageMeter.NetworkController.PacketAnalysisLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
DamageMeter
System.DivideByZeroException: Attempted to divide by zero.
   at DamageMeter.DataExporter.ToTeraDpsApi(SDespawnNpc despawnNpc)
   at DamageMeter.NetworkController.PacketAnalysisLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Void ToTeraDpsApi(Tera.Game.Messages.SDespawnNpc)
`
Windows 7 64bit. All pre-requisities were met - v0.7X were working just fine.
Tera EU.

**Comment by neowutran** [comment]
ok, you were on what area?

**Comment by mohrad-m** [comment]
Island of Dawn, the camp between Naga Battlemasters and Ice Giants.

**Comment by neowutran** [comment]
ok thanks, I think I know why. That should be fixed with the next release (v0.81)

**Comment by neowutran** [comment]
should be fixed (v0.81)
