### ISSUE TITLE
[Found in debug.txt] clipboard

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#91]
Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at DamageMeter.CopyPaste.Copy(IEnumerable`1 playerInfos, Int64 totalDamage, Int64 partyDps, Int64 firstHit, Int64 lastHit, Entity currentBoss, Boolean timedEncounter, String header, String content, String footer, String orderby, String order)
   at DamageMeter.NetworkController.CopyThread(List`1 stats, Int64 total, Int64 partyDps, Int64 firstHit, Int64 lastHit, Entity currentBoss, Boolean timedEncounter, CopyKey copy)
   at DamageMeter.NetworkController.<>c__DisplayClass59_0.<PacketAnalysisLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Windows.Forms
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at DamageMeter.CopyPaste.Copy(IEnumerable`1 playerInfos, Int64 totalDamage, Int64 partyDps, Int64 firstHit, Int64 lastHit, Entity currentBoss, Boolean timedEncounter, String header, String content, String footer, String orderby, String order)
   at DamageMeter.NetworkController.CopyThread(List`1 stats, Int64 total, Int64 partyDps, Int64 firstHit, Int64 lastHit, Entity currentBoss, Boolean timedEncounter, CopyKey copy)
   at DamageMeter.NetworkController.<>c__DisplayClass59_0.<PacketAnalysisLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

solution:
http://stackoverflow.com/questions/5707990/requested-clipboard-operation-did-not-succeed

**Comment by neowutran** [comment]
hum, better, just remove the access of clipboard for pasting dps, remove the STA from the thread. => problem solved & pasting more faster
