### ISSUE TITLE
[found in debug.txt] Another network error? 

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#96]
##### CRASH (version=0.85): #####
ìŒìˆ˜ê°€ ì•„ë‹Œ ìˆ«ìžì—¬ì•¼ í•©ë‹ˆë‹¤.
ë§¤ê°œ ë³€ìˆ˜ ì´ë¦„: length
   ìœ„ì¹˜: System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   ìœ„ì¹˜: Tera.PacketLog.BlockSplitter.PopBlock(MemoryStream stream)
   ìœ„ì¹˜: DamageMeter.Sniffing.TeraSniffer.HandleServerToClientDecrypted(Byte[] data)
   ìœ„ì¹˜: Tera.Sniffing.ConnectionDecrypter.OnServerToClientDecrypted(Byte[] data)
   ìœ„ì¹˜: Tera.Sniffing.ConnectionDecrypter.ServerToClient(Byte[] data)
   ìœ„ì¹˜: DamageMeter.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   ìœ„ì¹˜: NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   ìœ„ì¹˜: SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   ìœ„ì¹˜: SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   ìœ„ì¹˜: SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   ìœ„ì¹˜: SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   ìœ„ì¹˜: SharpPcap.LibPcap.PcapDevice.CaptureThread()
   ìœ„ì¹˜: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   ìœ„ì¹˜: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ìœ„ì¹˜: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ìœ„ì¹˜: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ìœ„ì¹˜: System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.ArgumentOutOfRangeException: ìŒìˆ˜ê°€ ì•„ë‹Œ ìˆ«ìžì—¬ì•¼ í•©ë‹ˆë‹¤.
ë§¤ê°œ ë³€ìˆ˜ ì´ë¦„: length
   ìœ„ì¹˜: System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   ìœ„ì¹˜: Tera.PacketLog.BlockSplitter.PopBlock(MemoryStream stream)
   ìœ„ì¹˜: DamageMeter.Sniffing.TeraSniffer.HandleServerToClientDecrypted(Byte[] data)
   ìœ„ì¹˜: Tera.Sniffing.ConnectionDecrypter.OnServerToClientDecrypted(Byte[] data)
   ìœ„ì¹˜: Tera.Sniffing.ConnectionDecrypter.ServerToClient(Byte[] data)
   ìœ„ì¹˜: DamageMeter.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   ìœ„ì¹˜: NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   ìœ„ì¹˜: NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   ìœ„ì¹˜: SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   ìœ„ì¹˜: SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   ìœ„ì¹˜: SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   ìœ„ì¹˜: SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   ìœ„ì¹˜: SharpPcap.LibPcap.PcapDevice.CaptureThread()
   ìœ„ì¹˜: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   ìœ„ì¹˜: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ìœ„ì¹˜: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ìœ„ì¹˜: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ìœ„ì¹˜: System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

**Comment by neowutran** [comment]
same as #94 ?

**Comment by Gl0** [comment]
This more likely packet loss/out-of-order/retransmission issue than 94.

**Comment by Gl0** [comment]
```
##### CRASH (version=0.88): #####
Non-negative number required.
Parameter name: length
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at Tera.PacketLog.BlockSplitter.PopBlock(MemoryStream stream)
   at DamageMeter.Sniffing.TeraSniffer.HandleServerToClientDecrypted(Byte[] data)
   at Tera.Sniffing.ConnectionDecrypter.OnServerToClientDecrypted(Byte[] data)
   at Tera.Sniffing.ConnectionDecrypter.ServerToClient(Byte[] data)
   at DamageMeter.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data)
   at NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data)
   at NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   at NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   at NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   at NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
Same issue with raw sockets.
